name: terraform plan

on:
  workflow_dispatch:
    branches:
      - dev   # Only allow manual runs from dev branch

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    # Needed for OIDC
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./terraform

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: gha-terraform-plan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform fmt (check)
        run: terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -out=plan.out

      - name: Show plan summary
        run: terraform show -no-color plan.out | tee plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            ./terraform/plan.out
            ./terraform/plan.txt

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        run: tflint || true